UU.write();
UT.write();
TT.write();
rhoU.write();
rhoT.write();

tau_mixI.write();
tau_mixK.write();
tau_mixM.write();
tau_chemFR.write();
tau_chemRR.write();

k_.write();
epsilon_.write();
mu_.write();
nu_.write();
Cp_.write();
alpha.write();
kappa.write();
kappaIFR.write();
kappaKFR.write();
kappaMFR.write();
kappaIRR.write();
kappaKRR.write();
kappaMRR.write();

FavUMean.write();
FavTMean.write();
FavUPrime.write();
FavTPrime.write();
FavUPrimeUPrime.write();
FavUPrimeTPrime.write();
FavTPrimeTPrime.write();
FavrhoUPrimeUPrime.write();
FavrhoUPrimeTPrime.write();
FavrhoTPrimeTPrime.write();

L_I.write();
L_K.write();
R_IK.write();
R_IM.write();
LESResIndex.write();
//FavgradUPrime.write();


